import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import {Window} from 'happy-dom';
import {evaluate,forecast} from '../src/model.js';
import {fictionalSample,toCSV} from '../src/data.js';
const w=new Window({url:'https://traywise.test',settings:{disableJavaScriptFileLoading:true,disableJavaScriptEvaluation:true,disableCSSFileLoading:true}});
globalThis.document=w.document;
document.write(await fs.readFile(new URL('../index.html',import.meta.url),'utf8'));
const {preparationRecord}=await import('../src/app.js');
const $=id=>document.getElementById(id);
const change=id=>$(id).dispatchEvent(new w.Event(id==='penalty'?'input':'change'));
const pause=()=>new Promise(r=>setTimeout(r,30));
function assertChoices(rows,date,event){const report=evaluate(rows);for(const penalty of [1,3,6]){const expected=forecast(report,date,event,penalty);const button=$('preference-'+penalty);for(const [metric,value] of [['quantity',String(expected.quantity)],['surplus',expected.expectedSurplus.toFixed(1)],['shortfall',expected.expectedShortfall.toFixed(1)]])assert.equal(button.querySelector('[data-metric='+metric+']').textContent,value);}}
async function upload(rows){Object.defineProperty($('csv'),'files',{configurable:true,value:[{name:'local.csv',size:100,text:async()=>toCSV(rows)}]});change('csv');await pause();}
test('source forecasts match sample acceptance values and comparisons',()=>{const rows=fictionalSample(),report=evaluate(rows);for(const [p,q,s,f] of [[1,104,'3.3','3.5'],[3,113,'9.4','0.6'],[6,114,'10.2','0.4']]){const result=forecast(report,'2026-09-21',0,p);assert.equal(result.quantity,q);assert.equal(result.expectedSurplus.toFixed(1),s);assert.equal(result.expectedShortfall.toFixed(1),f);assert.equal(result.point.toFixed(1),'103.7');assert.equal(result.band.lower,92);assert.equal(result.band.upper,115);}assertChoices(rows,'2026-09-21',0);});
test('presets and arbitrary integer slider synchronize plan, graph, live status and export',async()=>{const metrics=$('metrics').textContent;for(const penalty of [1,3,6,3,1,6]){$('preference-'+penalty).click();const record=await preparationRecord();assert.equal($('penalty').value,String(penalty));assert.equal($('penalty-value').textContent,String(penalty));assert.equal($('quantity').textContent,String(record.decision.quantity));assert.equal(record.decision.cUnder,penalty);assert.equal($('plot').querySelector('.prep-marker span').textContent,'Prep '+record.decision.quantity);assert.match($('status').textContent,new RegExp(record.decision.quantity+' portions'));for(const p of [1,3,6])assert.equal($('preference-'+p).getAttribute('aria-pressed'),String(p===penalty));}$('penalty').value=4;change('penalty');for(const p of [1,3,6])assert.equal($('preference-'+p).getAttribute('aria-pressed'),'false');assert.equal((await preparationRecord()).decision.cUnder,4);assert.equal($('metrics').textContent,metrics);});
test('date, event, dataset and repeated inputs recompute from the same forecast function',async()=>{for(const [date,event] of [['2026-09-22',1],['2026-10-01',0],['2026-09-22',1]]){$('date').value=date;$('event').checked=Boolean(event);change('date');change('event');assertChoices(fictionalSample(),date,event);}const rows=fictionalSample().map(r=>({...r,event:1-r.event}));await upload(rows);assertChoices(rows,$('date').value,0);$('event').checked=true;change('event');assertChoices(rows,$('date').value,1);});
test('pending and invalid imports hide stale comparisons and block export until valid recovery',async()=>{let resolveText;Object.defineProperty($('csv'),'files',{configurable:true,value:[{name:'bad.csv',size:100,text:()=>new Promise(r=>resolveText=r)}]});change('csv');assert.equal($('plan-content').hidden,true);assert.equal($('preparation-comparison').hidden,true);assert.equal($('export').disabled,true);await assert.rejects(preparationRecord());resolveText('invalid');await pause();assert.equal($('export').disabled,true);$('penalty').value=3;change('penalty');assert.equal($('preparation-comparison').hidden,true);await upload(fictionalSample());assert.equal($('preparation-comparison').hidden,false);assert.equal($('export').disabled,false);});
test('invalid date and insufficient evidence cannot expose stale comparisons',async()=>{$('date').value='2020-01-01';change('date');assert.equal($('preparation-comparison').hidden,true);await assert.rejects(preparationRecord());await upload(fictionalSample().slice(0,3));assert.equal($('plan-content').hidden,true);assert.equal($('preparation-comparison').hidden,true);assert.equal($('export').disabled,true);$('sample').click();assert.equal($('preparation-comparison').hidden,false);assertChoices(fictionalSample(),$('date').value,0);});
