import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import {Window} from 'happy-dom';
import {evaluate,MODEL_SPEC} from '../src/model.js';
import {toCSV,fictionalSample} from '../src/data.js';
import {constantHistory,unknownCalibration} from './readiness-fixtures.js';
const w=new Window({url:'https://traywise.test',settings:{disableJavaScriptFileLoading:true,disableJavaScriptEvaluation:true,disableCSSFileLoading:true}});
globalThis.document=w.document;document.write(await fs.readFile(new URL('../index.html',import.meta.url),'utf8'));
const {preparationRecord}=await import('../src/app.js');
const $=id=>document.getElementById(id);
const settle=()=>new Promise(setImmediate);
function startRead(name,text){Object.defineProperty($('csv'),'files',{configurable:true,value:[{name,size:100,text}]});$('csv').dispatchEvent(new w.Event('change'));}
async function upload(rows){startRead('synthetic.csv',async()=>toCSV(rows));await settle();}
function checkBlocks(rows){const report=evaluate(rows);assert.equal($('data-readiness').hidden,false);for(const [block,required] of Object.entries(MODEL_SPEC.minLabels)){const card=$('readiness-'+block);assert.equal(card.querySelector('[data-metric=labels]').textContent,report.eligibleCounts[block]+' / '+required);assert.equal(card.querySelector('[data-metric=deficit]').textContent,String(Math.max(0,required-report.eligibleCounts[block])));assert.deepEqual([...card.querySelectorAll('time')].map(el=>el.dateTime),report.splitDates[block].length>1?[report.splitDates[block][0],report.splitDates[block].at(-1)]:report.splitDates[block]);assert.match(card.querySelector('.readiness-observations').textContent,new RegExp(report.splitDates[block].length-report.eligibleCounts[block]+' unknown demand'));}}
test('chronological readiness uses actual all-row block dates, known labels and deficits',async()=>{const rows=constantHistory(48);assert.deepEqual(evaluate(rows).eligibleCounts,{train:28,calibration:9,holdout:11});await upload([...rows].reverse());checkBlocks(rows);assert.equal($('readiness-calibration').querySelector('[data-metric=deficit]').textContent,'1');assert.match($('status').textContent,/Calibration is 1 known label below its minimum/);const censored=constantHistory(60,unknownCalibration);assert.deepEqual(evaluate(censored).eligibleCounts,{train:36,calibration:0,holdout:12});await upload(censored);checkBlocks(censored);assert.equal($('readiness-calibration').querySelector('[data-metric=deficit]').textContent,'10');assert.match($('readiness-calibration').textContent,/12 unknown demand/);});
test('empty chronological blocks show no service rows without invented dates or labels',async()=>{const rows=constantHistory(1);await upload(rows);checkBlocks(rows);assert.equal($('readiness-train').querySelector('.readiness-dates').textContent,'No service rows');assert.equal($('readiness-calibration').querySelector('.readiness-dates').textContent,'No service rows');});
test('insufficient to valid to invalid to sample reset prevents stale readiness, plan and export',async()=>{await upload(constantHistory(48));await assert.rejects(preparationRecord());assert.equal($('plan-content').hidden,true);assert.equal($('preparation-comparison').hidden,true);assert.equal($('export').disabled,true);await upload(constantHistory(50));assert.equal($('data-readiness').hidden,true);assert.equal($('readiness-blocks').children.length,0);assert.deepEqual((await preparationRecord()).evaluation.eligibleCounts,{train:30,calibration:10,holdout:10});startRead('bad.csv',async()=>'invalid');await settle();assert.equal($('data-readiness').hidden,true);assert.equal($('plan-content').hidden,true);assert.equal($('export').disabled,true);await assert.rejects(preparationRecord());$('sample').click();assert.equal($('data-readiness').hidden,true);assert.equal($('export').disabled,false);assert.equal((await preparationRecord()).isFictionalDemo,true);});
test('inspection action selects data and moves focus to its keyboard tab',async()=>{await upload(constantHistory(48));$('inspect-readiness-data').click();assert.equal($('panel-data').hidden,false);assert.equal($('tab-data').getAttribute('aria-selected'),'true');assert.equal(document.activeElement.id,'tab-data');assert.equal($('export').disabled,true);$('tab-data').dispatchEvent(new w.KeyboardEvent('keydown',{key:'Home'}));assert.equal($('panel-plan').hidden,false);});
test('delayed imports cannot overwrite sample reset or reintroduce stale error/readiness',async()=>{for(const rejectOld of [false,true]){let resolve,reject;startRead('delayed.csv',()=>new Promise((a,b)=>{resolve=a;reject=b;}));assert.equal($('data-readiness').hidden,true);assert.equal($('readiness-blocks').children.length,0);assert.equal($('export').disabled,true);$('sample').click();if(rejectOld)reject(Error('old read failed'));else resolve(toCSV(constantHistory(48)));await settle();assert.equal($('source-name').textContent,'Fictional campus kitchen');assert.equal($('error').hidden,true);assert.equal($('data-readiness').hidden,true);assert.equal((await preparationRecord()).isFictionalDemo,true);}});
test('newest overlapping import alone controls readiness; stale completion cannot replace it',async()=>{let resolve;startRead('older.csv',()=>new Promise(r=>resolve=r));await upload(constantHistory(50));resolve(toCSV(constantHistory(60,unknownCalibration)));await settle();assert.equal($('data-readiness').hidden,true);assert.equal((await preparationRecord()).inputs.length,50);let reject;startRead('old-failure.csv',()=>new Promise((_,r)=>reject=r));await upload(constantHistory(48));reject(Error('old read failed'));await settle();checkBlocks(constantHistory(48));assert.equal($('error').hidden,true);assert.equal($('export').disabled,true);});
