import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';import {Window} from 'happy-dom';
const window=new Window({url:'https://traywise.test',settings:{disableJavaScriptFileLoading:true,disableJavaScriptEvaluation:true,disableCSSFileLoading:true}});globalThis.document=window.document;document.write(await fs.readFile(new URL('../index.html',import.meta.url),'utf8'));const {preparationRecord}=await import('../src/app.js');const $=id=>document.getElementById(id);const change=id=>$(id).dispatchEvent(new window.Event('change',{bubbles:true}));
test('initial UI labels fiction and exposes working plan and all candidates',()=>{assert.equal($('source-label').textContent,'DEMO DATA · NOT REAL OUTCOMES');assert.match($('quantity').textContent,/^\d+$/);assert.equal($('metrics').children.length,3);assert.equal($('data-rows').children.length,112);assert.equal($('error').hidden,true);});
test('slider updates integer recommendation without decreasing it and preserves held-out metrics',()=>{const metrics=$('metrics').textContent;let previous=0;for(let i=1;i<=10;i++){$('penalty').value=i;$('penalty').dispatchEvent(new window.Event('input'));const q=Number($('quantity').textContent);assert.ok(q>=previous);previous=q;}assert.equal($('penalty-value').textContent,'10');assert.equal($('metrics').textContent,metrics);});
test('tabs expose accessible keyboard navigation',()=>{$('tab-plan').dispatchEvent(new window.KeyboardEvent('keydown',{key:'ArrowRight',bubbles:true}));assert.equal($('tab-evidence').getAttribute('aria-selected'),'true');assert.equal($('panel-plan').hidden,true);assert.equal($('panel-evidence').hidden,false);assert.equal(document.activeElement.id,'tab-evidence');$('tab-data').click();assert.equal($('panel-data').hidden,false);});
test('invalid next date hides stale plan and recovery works',async()=>{const old=$('date').value;$('date').value='2020-01-01';change('date');assert.equal($('plan-content').hidden,true);assert.equal($('error').hidden,false);assert.equal($('export').disabled,true);await assert.rejects(preparationRecord(),/valid preparation/);$('date').value=old;change('date');assert.equal($('plan-content').hidden,false);assert.equal($('error').hidden,true);});
test('export is reproducible and contains exact protocol, data, split and decision',async()=>{const a=await preparationRecord(),b=await preparationRecord();assert.deepEqual(a,b);assert.equal(a.isFictionalDemo,true);assert.equal(a.inputs.length,112);assert.match(a.dataSHA256,/^[0-9a-f]{64}$/);assert.equal(a.decision.cUnder,10);assert.equal(a.evaluation.models.ridge.coefficients.length,9);});
test('malicious CSV filename is rendered only as text; invalid import preserves earlier dataset',async()=>{const valid=await fs.readFile(new URL('../data/fictional-kitchen.csv',import.meta.url),'utf8');const input=$('csv');Object.defineProperty(input,'files',{configurable:true,value:[{name:'<img src=x onerror=alert(1)>.csv',size:valid.length,text:async()=>valid}]});change('csv');await new Promise(r=>setTimeout(r,20));assert.equal($('source-name').children.length,0);assert.match($('source-name').textContent,/<img/);assert.equal($('source-label').textContent,'DEMO DATA · NOT REAL OUTCOMES');assert.equal((await preparationRecord()).isFictionalDemo,true);const quantity=$('quantity').textContent;Object.defineProperty(input,'files',{configurable:true,value:[{name:'bad.csv',size:10,text:async()=>'=HYPERLINK("x")'}]});change('csv');await new Promise(r=>setTimeout(r,20));assert.equal($('error').hidden,false);assert.equal($('quantity').textContent,quantity);assert.match($('error').textContent,/previous dataset/);$('sample').click();assert.equal($('source-name').textContent,'Fictional campus kitchen');});
test('runtime has no upload, fetch, telemetry, external asset or HTML injection sink',async()=>{const js=await fs.readFile(new URL('../src/app.js',import.meta.url),'utf8');assert.doesNotMatch(js,/\bfetch\s*\(|XMLHttpRequest|sendBeacon|innerHTML|insertAdjacentHTML|localStorage/);const html=await fs.readFile(new URL('../index.html',import.meta.url),'utf8');assert.doesNotMatch(html,/(?:src|href)=["']https?:/);const css=await fs.readFile(new URL('../src/style.css',import.meta.url),'utf8');assert.doesNotMatch(css,/@import|https?:/);const server=await fs.readFile(new URL('../server.js',import.meta.url),'utf8');assert.match(server,/connect-src 'none'/);});
