import {evaluate,forecast,MODEL_SPEC,PROTOCOL_VERSION} from './model.js';
import {fictionalSample,parseCSV,toCSV,describeData} from './data.js';
const $=id=>document.getElementById(id);const names={ridge:'Learned ridge model',weekdayMedian:'Same-weekday median',recentMean:'Recent-seven average'};
let rows=[],report=null,plan=null,source='Fictional campus kitchen',isDemo=true,importGeneration=0,exportInFlight=false;
const fmt=n=>Number.isFinite(n)?n.toFixed(1):'—';
function set(id,value){$(id).textContent=value;}
function cell(row,text){const td=document.createElement('td');td.textContent=text;row.append(td);}
function clear(id){$(id).replaceChildren();}
function announce(text){set('status',text);}
function fail(message){set('error',message);$('error').hidden=false;announce(message);}
function tableRow(id,values,selected=false){const tr=document.createElement('tr');if(selected)tr.className='selected-row';values.forEach(v=>cell(tr,v));$(id).append(tr);}
function load(next,title,demo){demo=demo||toCSV(next)===toCSV(fictionalSample());rows=next;source=title;isDemo=demo;report=evaluate(rows);$('error').hidden=true;set('source-name',title);set('source-label',demo?'DEMO DATA · NOT REAL OUTCOMES':'LOCAL CSV · USER-SUPPLIED COUNTS');const d=describeData(rows);set('days',d.total);set('known',d.known);set('censored',d.censored);set('quality-note',`${d.censored} unknown-demand services are excluded from fitting and exact scoring. ${d.gaps?`${d.gaps} date gaps are preserved, not filled with zeros.`:'No missing calendar dates.'}`);const nextDate=new Date(Date.parse(rows.at(-1).date+'T00:00:00Z')+86400000).toISOString().slice(0,10);$('date').value=nextDate;$('date').min=nextDate;$('event').checked=false;renderEvidence();renderData();renderPlan();announce(`Loaded ${d.total} service days. ${d.known} known-demand labels.`);}
function renderPlan(){const ready=report?.status==='ready';$('insufficient').hidden=ready;$('plan-content').hidden=!ready;$('export').disabled=!ready||exportInFlight;if(!ready){plan=null;set('insufficient','Insufficient evidence for a preparation plan. Need at least 28 known labels in training, 10 in calibration and 10 in holdout. Unknown-demand rows do not count. You can still inspect the imported data.');return;}const date=$('date').value;const valid=/^\d{4}-\d{2}-\d{2}$/.test(date)&&Number.isFinite(Date.parse(date+'T00:00:00Z'))&&date>rows.at(-1).date;if(!valid){plan=null;$('export').disabled=true;fail('Choose a real service date after the last imported service. The previous plan is hidden until the date is valid.');$('plan-content').hidden=true;return;}const penalty=Number($('penalty').value);set('penalty-value',penalty);plan=forecast(report,date,Number($('event').checked),penalty);set('quantity',plan.quantity);set('model-label',names[report.selectedModel]+' · selected using training only');set('band',`${plan.band.lower}–${plan.band.upper} portions`);set('surplus',fmt(plan.expectedSurplus));set('shortfall',fmt(plan.expectedShortfall));set('scenario-note',`${plan.scenarioCount} historical-error scenarios · ${Math.round(plan.quantile*100)}th scenario percentile preference. Estimates, not actual outcomes.`);set('point-label',`Point forecast: ${fmt(plan.point)} requests`);const m=report.models[report.selectedModel],coverage=m.coverage.covered/m.coverage.eligible;const warnings=[...plan.warnings];if(coverage<.8)warnings.push(`Observed band coverage was only ${m.coverage.covered}/${m.coverage.eligible} known held-out days (${Math.round(coverage*100)}%). Review this plan; the nominal 80% is not a guarantee.`);if(m.mae>Math.min(report.models.weekdayMedian.mae,report.models.recentMean.mae)+1e-9)warnings.push('The training-selected model lost to a simple baseline on holdout. Review the evidence before preparing.');if(isDemo)warnings.push('Fictional sample only. No actual food or carbon savings have been measured.');warnings.push('The model and calibration stay frozen on earlier blocks for this reproducible prototype.');set('forecast-warnings',warnings.join(' '));plot();}
function plot(){clear('plot');const min=Math.max(0,Math.floor(Math.min(...plan.scenarios,plan.quantity)/10)*10-10),max=Math.ceil(Math.max(...plan.scenarios,plan.quantity)/10)*10+10;const pos=n=>5+90*(n-min)/(max-min);const track=document.createElement('div');track.className='plot-track';$('plot').append(track);const buckets=new Map();for(const value of plan.scenarios){const bucket=Math.round(pos(value)/2);const level=buckets.get(bucket)||0;buckets.set(bucket,level+1);const dot=document.createElement('span');dot.className='scenario-dot';dot.style.left=pos(value)+'%';dot.style.bottom=(28+level%5*12)+'px';$('plot').append(dot);}const marker=document.createElement('div');marker.className='prep-marker';marker.style.left=pos(plan.quantity)+'%';const label=document.createElement('span');label.textContent='Prep '+plan.quantity;marker.append(label);$('plot').append(marker);for(let i=0;i<=4;i++){const value=min+(max-min)*i/4;const tick=document.createElement('span');tick.className='tick';tick.style.left=pos(value)+'%';tick.textContent=Math.round(value);$('plot').append(tick);}$('plot').setAttribute('aria-label',`${plan.scenarioCount} historical-error demand scenarios range from ${fmt(Math.min(...plan.scenarios))} to ${fmt(Math.max(...plan.scenarios))} requests. Preparation ${plan.quantity} portions.`);}
function renderEvidence(){clear('metrics');clear('daily');const counts=report.eligibleCounts;set('split-note',`Known labels: ${counts.train} train / ${counts.calibration} calibration / ${counts.holdout} holdout. Split dates are fixed before excluding unknown-demand rows.`);if(report.status!=='ready'){set('evidence-warning',report.warnings.at(-1));set('fit-details','Model unavailable: insufficient known-label evidence.');set('daily-caption','No scored holdout available.');return;}for(const name of MODEL_SPEC.tieOrder){const m=report.models[name];tableRow('metrics',[names[name]+(name===report.selectedModel?' · selected':''),fmt(m.mae),fmt(m.rmse),`${m.coverage.covered}/${m.coverage.eligible} (${Math.round(100*m.coverage.covered/m.coverage.eligible)}%)`,fmt(m.asymmetricLoss)],name===report.selectedModel);}const m=report.models[report.selectedModel];set('evidence-warning',`${isDemo?'Fictional data. ':''}Nominal 80% historical residual bands are not individual-day guarantees. ${m.excluded} held-out services have unknown demand and are excluded from exact scores; ${m.lowerBoundViolations} lower-bound band violations. Selected mean band width: ${fmt(m.meanWidth)} portions. `+(m.mae>Math.min(report.models.weekdayMedian.mae,report.models.recentMean.mae)+1e-9?'The selected model loses to a baseline on this holdout. Selection is not changed after seeing that result.':'These results do not establish performance at a real kitchen.'));set('fit-details',JSON.stringify({protocol:PROTOCOL_VERSION,lambda:5,features:MODEL_SPEC.features,coefficients:report.models.ridge.coefficients,scaling:report.models.ridge.scaling,selectionMAE:Object.fromEntries(Object.entries(report.selectionScores).map(([k,v])=>[k,v.mae])),dateBlocks:report.splitDates},null,2));set('daily-caption',names[report.selectedModel]+' · fixed held-out predictions');for(const d of m.perDay)tableRow('daily',[d.date,d.censored?'Unknown; ≥'+d.lowerBound:d.target,fmt(d.point),`${d.band.lower}–${d.band.upper}`,d.quantity,d.censored?'Not scored':fmt(d.error)]);}
function renderData(){clear('data-rows');for(const r of rows)tableRow('data-rows',[r.date,r.prepared,r.served,r.leftovers,r.observation_status.replaceAll('_',' '),r.censored?'Unknown; ≥'+r.lowerBound:r.target]);}
function download(text,filename,type){const blob=new Blob([text],{type});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=filename;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
export async function preparationRecord(){if(!plan||report?.status!=='ready')throw Error('A valid preparation plan is required before exporting.');const snapshot=structuredClone({product:'TrayWise',formatVersion:1,engineSHA256:'3c1fffc956c5b167aa27ae86d77c5b04ca3aee3b27150be463a6d30262ef4d9b',protocolVersion:PROTOCOL_VERSION,source,isFictionalDemo:isDemo,modelSpec:MODEL_SPEC,inputs:rows,decision:{cOver:1,cUnder:Number($('penalty').value),...plan},evaluation:report,limitations:['Historical error scenarios are not guaranteed future demand.','Unknown-demand exclusions may bias evaluation.','No measured food, carbon or financial savings.','Complete requests measure recorded requests, not latent appetite.']});const csv=toCSV(snapshot.inputs);const digest=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(csv));return {...snapshot,dataSHA256:[...new Uint8Array(digest)].map(n=>n.toString(16).padStart(2,'0')).join('')};}
$('export').addEventListener('click',async()=>{if(exportInFlight)return;exportInFlight=true;try{$('export').disabled=true;const record=await preparationRecord();download(JSON.stringify(record,null,2),`traywise-prep-${record.decision.date}.json`,'application/json');announce('Preparation record downloaded.');}catch{fail('Could not export the record. Choose a valid plan and use a secure browser context.');}finally{exportInFlight=false;$('export').disabled=!plan||report?.status!=='ready';}});
$('csv').addEventListener('change',async e=>{const generation=++importGeneration;const file=e.target.files?.[0];if(!file)return;try{announce('Checking local CSV…');if(file.size>1_000_000)throw Error('Use a CSV smaller than 1 MB.');const text=await file.text();if(generation!==importGeneration)return;load(parseCSV(text),file.name,false);}catch(error){if(generation===importGeneration)fail(error.message+' Your previous dataset and plan are unchanged.');}finally{e.target.value='';}});
$('sample').addEventListener('click',()=>{importGeneration++;load(fictionalSample(),'Fictional campus kitchen',true);});$('template').addEventListener('click',()=>download(toCSV(fictionalSample()),'traywise-fictional-sample.csv','text/csv'));
for(const id of ['date','event','penalty'])$(id).addEventListener(id==='penalty'?'input':'change',()=>{$('error').hidden=true;renderPlan();announce(plan?`Plan updated: ${plan.quantity} portions.`:'Plan unavailable.');});
const tabs=['plan','evidence','data'];function selectTab(name){for(const tab of tabs){const active=tab===name;$('tab-'+tab).setAttribute('aria-selected',String(active));$('tab-'+tab).tabIndex=active?0:-1;$('panel-'+tab).hidden=!active;}}tabs.forEach((name,i)=>{$('tab-'+name).addEventListener('click',()=>selectTab(name));$('tab-'+name).addEventListener('keydown',event=>{let index;if(event.key==='ArrowRight')index=(i+1)%3;if(event.key==='ArrowLeft')index=(i+2)%3;if(event.key==='Home')index=0;if(event.key==='End')index=2;if(index!==undefined){event.preventDefault();selectTab(tabs[index]);$('tab-'+tabs[index]).focus();}});});
load(fictionalSample(),'Fictional campus kitchen',true);
